[package]
name = "audioscope"
version = "0.1.0"
authors = ["delu <davidelu93@gmail.com>"]

[dependencies]
toml = "0.2.1"
rustc-serialize = "*"
glium = "0.16.0"
portaudio = { git = "https://github.com/khimaros/rust-portaudio" }
num = "*"
rustfft = "4.0.0"
